name: iplessipbus
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - openjdk
  - sbt
  - git
  - gxx
  - black
  - python=3.11
  - pip
  - pandas
  - numpy
  - uncrustify
  - include-what-you-use
  - clang-format
  - clang-tools
  - cppcheck
  - cpplint
  - pip:
    - pylint
    - coloredlogs
    - pre-commit
    - zeroconf
    - psutil
    - matplotlib
    - seaborn
    - CLinters
    - cocotb
    - pytest
    - IPython
    - cocotbext-eth
    - cocotbext-axi
variables:
  X_SCLS: 1